<?php
/**
 * AJAX endpoint: Send welcome email to a newly created user.
 *
 * Expects POST with JSON body:
 *   { "to_email", "to_name", "employee_id", "password" }
 *
 * Returns JSON:
 *   { "success": true/false, "method": "smtp"|"mail"|"none", "error": "" }
 */

// Suppress PHP warnings/notices from appearing in the output (they break JSON parsing)
error_reporting(0);
ini_set('display_errors', 0);

// Buffer all output so stray warnings never leak into the JSON response
ob_start();

try {
    require_once __DIR__ . '/includes/config.php';
    require_once __DIR__ . '/includes/functions.php';

    // Discard any output generated by includes (e.g. deprecation notices)
    ob_clean();

    header('Content-Type: application/json; charset=utf-8');

    // Only accept POST
    if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
        http_response_code(405);
        echo json_encode(['success' => false, 'error' => 'Method not allowed.']);
        exit;
    }

    // Verify the user is logged in and is a Quest Lead
    $role = $_SESSION['role'] ?? '';
    if ($role === 'hybrid') $role = 'quest_lead';
    elseif ($role === 'quest_giver') $role = 'quest_lead';
    elseif ($role === 'contributor') $role = 'quest_lead';

    if ($role !== 'quest_lead') {
        http_response_code(403);
        echo json_encode(['success' => false, 'error' => 'Access denied. Only Quest Leads can send welcome emails.']);
        exit;
    }

    // Parse JSON body (or fall back to form data)
    $input = json_decode(file_get_contents('php://input'), true);
    if (!$input) {
        // Try regular POST params
        $input = $_POST;
    }

    $to_email    = trim($input['to_email']    ?? '');
    $to_name     = trim($input['to_name']     ?? '');
    $employee_id = trim($input['employee_id'] ?? '');
    $password    = $input['password']          ?? '';

    // Validate required fields
    if (empty($to_email) || empty($to_name) || empty($employee_id) || empty($password)) {
        http_response_code(400);
        echo json_encode(['success' => false, 'error' => 'Missing required fields (to_email, to_name, employee_id, password).']);
        exit;
    }

    if (!filter_var($to_email, FILTER_VALIDATE_EMAIL)) {
        http_response_code(400);
        echo json_encode(['success' => false, 'error' => 'Invalid recipient email address.']);
        exit;
    }

    // Use the Quest Lead's email as Reply-To so replies go back to them
    $reply_to = $_SESSION['email'] ?? '';

    // Send the email
    $result = send_welcome_email($to_email, $to_name, $employee_id, $password, $reply_to);

    // Discard any stray output from the send process
    ob_clean();

    if ($result['success'] ?? false) {
        echo json_encode([
            'success' => true,
            'method'  => $result['method'] ?? 'unknown',
            'error'   => ''
        ]);
    } else {
        echo json_encode([
            'success' => false,
            'method'  => 'none',
            'error'   => $result['error'] ?? 'Unknown error occurred while sending email.'
        ]);
    }

} catch (Throwable $e) {
    // Catch ANY fatal error / exception and still return valid JSON
    ob_clean();
    header('Content-Type: application/json; charset=utf-8');
    error_log('send_welcome_email.php fatal error: ' . $e->getMessage());
    echo json_encode([
        'success' => false,
        'method'  => 'none',
        'error'   => 'Server error: ' . $e->getMessage()
    ]);
}

ob_end_flush();
